//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment1
    {
        public int Comment_ID { get; set; }
        public string Comment_Text { get; set; }
        public int Task_ID { get; set; }
        public int User_ID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
