//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Report_ID { get; set; }
        public int Task_ID { get; set; }
        public int Taks_Responsive_UserID { get; set; }
        public int Report_Working_Time { get; set; }
        public bool Report_Status { get; set; }
        public string Report_Done_Comment { get; set; }
        public int User_ReportID { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual User User { get; set; }
    }
}
