//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.Comments1 = new HashSet<Comment1>();
        }
    
        public int Task_ID { get; set; }
        public string Task_Title { get; set; }
        public string Task_Text { get; set; }
        public int Task_Responsive_User_ID { get; set; }
        public int Task_Difficulty_Time { get; set; }
        public int Task_Created_User_ID { get; set; }
        public System.DateTime Task_Created_Date { get; set; }
        public Nullable<System.DateTime> Task_Last_Edit_Date { get; set; }
        public bool Task_Status { get; set; }
        public int Task_TimeWorked { get; set; }
    
        public virtual Report Report { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<Comment1> Comments1 { get; set; }
    }
}
